# https://github.com/golangci/golangci-lint
name: Continuous Integration
on:
  push:
    # prevent duplication of tests with
    # `pull_request` event
    branches:
      - master
  pull_request:

jobs:
  golang_lint:
    name: Code style
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        id: checkout
        with:
          fetch-depth: 10

      - name: Run Golang CI Lint
        uses: reviewdog/action-golangci-lint@v2
        id: lint
        with: 
          # Checks are implemented only for new changes
          golangci_lint_flags: ""

      - name: Generate coverage doc
        uses: gwatts/go-coverage-action@v1
        id: coverage
        with:
          coverage-threshold: 85
      
      - name: Upload coverage doc and test info as artifact
        uses: actions/upload-artifact@v3
        id: artifact-upload
        if: always()
        with: 
          path: ${{ steps.coverage.outputs.report-pathname }}
          if-no-files-found: error

  golang_test:
    name: Code tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        id: checkout

      - name: Setup gotestfmt
        uses: haveyoudebuggedit/gotestfmt-action@v2
        id: testfmt
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run go tests
        id: test
        run: |
          set -euo pipefail
          go test -json -v ./... 2>&1 | tee /tmp/gotest.log | gotestfmt

      - name: Upload test info as artifact
        uses: actions/upload-artifact@v3
        id: artifact-upload
        with: 
          path: /tmp/gotest.log
          if-no-files-found: error

