# https://github.com/golangci/golangci-lint
name: Continuous Integration
on:
  push:
    # prevent duplication of tests with
    # `pull_request` event
    branches:
      - master
  pull_request:

jobs:
  golang_lint_and_test:
    name: Code style and tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        id: checkout
        with:
          fetch-depth: 10

      - name: Run Golang CI Lint
        uses: reviewdog/action-golangci-lint@v2
        id: lint
        with: 
          # Checks are implemented only for new changes
          golangci_lint_flags: "--new-from-rev=HEAD~1"

      - name: Setup gotestfmt
        uses: haveyoudebuggedit/gotestfmt-action@v2
        id: testfmt

      - name: Run go tests
        id: test
        run: |
          set -euo pipefail
          go test -json -v ./... 2>&1 | tee /tmp/gotest.log | gotestfmt
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate coverage doc
        uses: gwatts/go-coverage-action@v1
        id: coverage
        with:
          coverage-threshold: 90
      
      - name: Upload coverage doc as artifact
        uses: actions/upload-artifact@v3
        id: artifact-upload
        with: 
          path: |
            ${{ steps.coverage.outputs.report-pathname }}
            /tmp/gotest.log
          if-no-files-found: error

